AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: This Template deploys 1 ALB with 1 TargetGroup, 1 AutoScalingGroup with 1 LaunchConfiguration and 2 SecurityGroups

# Input Parameter go here
Parameters:
  EnvironmentName:
    Description: Will be used as name for all Resources (lowercase only!)
    Type: String
    AllowedPattern: '[a-z]+'
  LambdaS3GetBucket:
    Description: Bucket that Lambda needs to access
    Type: String

    
# All Resources go here
Resources:


  # # Lambda Function
  # LambdaFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     #FunctionName: !Sub lambda_${EnvironmentName}
  #     #Handler: index.handler
  #     #Runtime: nodejs6.10
  #     #MemorySize: 512
  #     #Timeout: 30
  #     #Role: !GetAtt LambdaExecutionRole.Arn
  #     # CodeUri: '../lambda/'
  #     #Environment:
  #     #  Variables:
  #     #    SNS_TOPIC: !Ref SNSTopic
  #     Events:
  #       S3:
  #         Type: S3
  #         Properties:
  #           Bucket: !Ref LambdaS3GetBucket
  #           Events: s3:ObjectCreated:*



# Outputs go here
Outputs:
