AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Creates an API Gateway that calls a Lambda function
Resources:
  LambdaAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: './lambda_function.py'
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /
            Method: get